services:
  - type: web
    name: my-flask-summarizer
    env: python
    build:
      context: .
      dockerfile: Dockerfile  # Use custom Dockerfile
    run:
      command: gunicorn --bind 0.0.0.0:10000 app:app
